/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * confSigProc.java
 *
 * Created on 28-11-2014, 01:52:11 AM
 */

package gui;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author carlos
 */
public class confSigProc extends javax.swing.JPanel {
    private JPanel panelBase;
    private JFrame ventana;
    /** Creates new form confSigProc */
    public confSigProc(JPanel pan, JFrame vt) {
        initComponents();
        this.setSize(pan.getSize());
        panelBase = pan;
        ventana = vt;
    }

    public int getNroProcesos(){
        int res =0;
        res = jcmbNroProcesos.getSelectedIndex();
        return res;
    }

    public String getProximoProceso(){
        String res="";
        res = (String) jcmbTipoProxProc.getSelectedItem();
        return res;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbNroProcesos = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jLabel4 = new javax.swing.JLabel();
        jcmbTipoProxProc = new org.edisoncor.gui.comboBox.ComboBoxRect();

        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(-14336,true));
        jLabel1.setText("Configuraciones Siguiente");

        jLabel2.setText("Nro. Procesos:");

        jLabel3.setForeground(new java.awt.Color(-14336,true));
        jLabel3.setText("Proceso");

        jcmbNroProcesos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel4.setText("Eligir Proximo Proceso:");

        jcmbTipoProxProc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "mas corto", "mas largo" }));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2))
                            .addComponent(jcmbNroProcesos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jcmbTipoProxProc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbNroProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcmbTipoProxProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        add(panel1);
        panel1.setBounds(0, 0, 250, 300);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.comboBox.ComboBoxRect jcmbNroProcesos;
    private org.edisoncor.gui.comboBox.ComboBoxRect jcmbTipoProxProc;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables



}
