/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * confRaundRobin.java
 *
 * Created on 28-11-2014, 12:39:49 AM
 */

package gui;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author carlos
 */
public class confRaundRobin extends javax.swing.JPanel {
    private JPanel panelBase;
    private JFrame ventana;
    /** Creates new form confRaundRobin */
    public confRaundRobin(JPanel pan, JFrame vt) {
        initComponents();
        
        this.setSize(pan.getSize());
        panelBase = pan;
        ventana = vt;
        inhabilitar();

    }

    private void habilitar(){
        jtxtTiempoProcesado.setEditable(true);
    }

    private void inhabilitar(){
        jtxtTiempoProcesado.setEditable(false);
        jtxtTiempoProcesado.setText("");
    }

    public int darNroProcesosRaundRobin(){
        int res=0;
        res = jcmbNroPorcesos.getSelectedIndex();
        return res;
    }

    public int darTiempoProcesadoQuantumRaundRobin(){
        int res = 0;
        res = Integer.parseInt(jtxtQuantum.getText());
        return res;
    }

    public String tipoProcesadoRaundRobin(){
        String res = "";
        res = (String) jcmbTipoProcesado.getSelectedItem();
        return res;
    }

    public int darTiempoProcesadoRaundRobin(){
        int res = 0;
        res = Integer.parseInt(jtxtTiempoProcesado.getText());
        return res;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTiempoProcesado = new org.edisoncor.gui.textField.TextField();
        jLabel4 = new javax.swing.JLabel();
        jcmbNroPorcesos = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jcmbTipoProcesado = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jLabel5 = new javax.swing.JLabel();
        jtxtQuantum = new org.edisoncor.gui.textField.TextField();

        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(-14336,true));
        jLabel1.setText("Configuraciones Raund Robin");

        jLabel2.setText("Nro. Procesos:");

        jLabel3.setText("Tiempo Del Procesador");

        jLabel4.setText("Tiempo quantum");

        jcmbNroPorcesos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jcmbTipoProcesado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "aleatorio", "constante" }));
        jcmbTipoProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipoProcesadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Tiempo Procesado");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcmbNroPorcesos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jcmbTipoProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jtxtTiempoProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jtxtQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jcmbNroPorcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbTipoProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtTiempoProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(panel1);
        panel1.setBounds(0, 0, 250, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbTipoProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoProcesadoActionPerformed
        // TODO add your handling code here:
        if (jcmbTipoProcesado.getSelectedItem()=="constante") {
            habilitar();
        }
    }//GEN-LAST:event_jcmbTipoProcesadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private org.edisoncor.gui.comboBox.ComboBoxRect jcmbNroPorcesos;
    private org.edisoncor.gui.comboBox.ComboBoxRect jcmbTipoProcesado;
    private org.edisoncor.gui.textField.TextField jtxtQuantum;
    private org.edisoncor.gui.textField.TextField jtxtTiempoProcesado;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
