/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * confAltoIndice.java
 *
 * Created on 28-11-2014, 01:48:02 PM
 */

package gui;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author carlos
 */
public class confAltoIndice extends javax.swing.JPanel {
    private JPanel panelBase;
    private JFrame ventana;
    /** Creates new form confAltoIndice */
    public confAltoIndice(JPanel pan, JFrame vt) {
        initComponents();
        this.setSize(pan.getSize());
        ventana = vt;
        panelBase = pan;
    }

    public void habilitar(){

    }

    public void inhabilitar(){

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnverTablaFifo = new org.edisoncor.gui.button.ButtonAction();
        jtxtNroProc = new org.edisoncor.gui.textField.TextField();
        jbtnOk = new org.edisoncor.gui.button.ButtonAction();
        jtxtTmpProc = new org.edisoncor.gui.textField.TextField();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(-14336,true));
        jLabel1.setText("Configuracion Alto Indice");

        jLabel2.setText("Nro. Procesos:");

        jbtnverTablaFifo.setText("Ver Tabla");
        jbtnverTablaFifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnverTablaFifoActionPerformed(evt);
            }
        });

        jbtnOk.setText("ON");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });

        jLabel4.setText("Tiempo procesado");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jtxtNroProc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jbtnverTablaFifo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtxtTmpProc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel4)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jtxtNroProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtxtTmpProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(jbtnverTablaFifo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panel1);
        panel1.setBounds(0, 0, 250, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnverTablaFifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnverTablaFifoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbtnverTablaFifoActionPerformed

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
        // TODO add your handling code here:
        habilitar();
}//GEN-LAST:event_jbtnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private org.edisoncor.gui.button.ButtonAction jbtnOk;
    private org.edisoncor.gui.button.ButtonAction jbtnverTablaFifo;
    private org.edisoncor.gui.textField.TextField jtxtNroProc;
    private org.edisoncor.gui.textField.TextField jtxtTmpProc;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
