/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ventAyuda.java
 *
 * Created on May 21, 2013, 11:01:21 AM
 */

package reportes;
import com.sun.pdfview.PDFFile;
import com.sun.pdfview.PDFPage;
import com.sun.pdfview.PagePanel;
import java.awt.Color;
import java.io.File;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
/**
 *
 * @author carlos
 */
public class ventAyuda extends javax.swing.JDialog
{
    // private String ruta="C:\\Program Files\\EmpresaABC\\manual_sistema.pdf";
    private String ruta="src//documentos//documento.pdf";
    private int pagina = 0;
    private int paginas = 100;
    private int number = 0;
    private PagePanel panel = new PagePanel();
    /** Creates new form ventAyuda */
    public ventAyuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        panel.setBounds(120,20,600,650);

        panel.setBackground(Color.WHITE);
        add(panel);
        initComponents();
        setSize(750, 720);
        //this.setLocation(900, 20);
        this.setLocationRelativeTo(null);
    }

    private void actualizar()
    {
        if(pagina>0)
        {
        jbtnCargarSigiente.setText("SIGUENTE");
        }
        else
        {
         jbtnCargarSigiente.setText("CARGAR");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jpanelSombra = new org.edisoncor.gui.panel.PanelShadow();
        jbtnCargarSigiente = new javax.swing.JButton();
        jbtnCargarAnterior = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panel1.setColorPrimario(new java.awt.Color(153, 153, 255));
        panel1.setGradiente(org.edisoncor.gui.panel.Panel.Gradiente.CENTRAL);
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/17.jpg"))); // NOI18N

        jpanelSombra.setDistance(10);

        jbtnCargarSigiente.setForeground(new java.awt.Color(0, 153, 0));
        jbtnCargarSigiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adelante.png"))); // NOI18N
        jbtnCargarSigiente.setText("CARGAR");
        jbtnCargarSigiente.setBorder(null);
        jbtnCargarSigiente.setBorderPainted(false);
        jbtnCargarSigiente.setContentAreaFilled(false);
        jbtnCargarSigiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCargarSigiente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCargarSigiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCargarSigiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargarSigienteActionPerformed(evt);
            }
        });

        jbtnCargarAnterior.setForeground(new java.awt.Color(0, 153, 0));
        jbtnCargarAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atraz.png"))); // NOI18N
        jbtnCargarAnterior.setText("ANTERIOR");
        jbtnCargarAnterior.setBorder(null);
        jbtnCargarAnterior.setBorderPainted(false);
        jbtnCargarAnterior.setContentAreaFilled(false);
        jbtnCargarAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCargarAnterior.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCargarAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCargarAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargarAnteriorActionPerformed(evt);
            }
        });

        jbtnSalir.setForeground(new java.awt.Color(0, 153, 0));
        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salidasss.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.setBorder(null);
        jbtnSalir.setBorderPainted(false);
        jbtnSalir.setContentAreaFilled(false);
        jbtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelSombraLayout = new javax.swing.GroupLayout(jpanelSombra);
        jpanelSombra.setLayout(jpanelSombraLayout);
        jpanelSombraLayout.setHorizontalGroup(
            jpanelSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelSombraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnCargarSigiente, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jbtnCargarAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(679, 679, 679))
        );
        jpanelSombraLayout.setVerticalGroup(
            jpanelSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelSombraLayout.createSequentialGroup()
                .addComponent(jbtnCargarSigiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCargarAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelSombra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelSombra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCargarSigienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargarSigienteActionPerformed
        // TODO add your handling code here:
       pagina+=1;
	 if(pagina>paginas||pagina<1)
         {
          pagina=1;
         }
            try {
             //Ojo con esto, aqui es donde se pone el nombre del archivo pdf, en este caso debe estar en el mismo
            File file = new File(ruta);
            //Ubicaci�n del archivo pdf
            RandomAccessFile raf = new RandomAccessFile(file, "r");
            FileChannel channel = raf.getChannel();

            MappedByteBuffer buf = channel.map(FileChannel.MapMode.READ_ONLY,0, channel.size());
            PDFFile pdffile = new PDFFile(buf);

            // muestra la pagina en la posici�n de la variable pagina page channel.size()
            PDFPage page = pdffile.getPage(pagina);
            paginas = pdffile.getNumPages(); //numero de paginas del documento
            panel.useZoomTool(false);
            panel.showPage(page);
            actualizar();
            }

            catch (Exception ex)
                            {
            ex.printStackTrace();
            }
                    repaint();
                    panel.repaint();
    }//GEN-LAST:event_jbtnCargarSigienteActionPerformed

    private void jbtnCargarAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargarAnteriorActionPerformed
        // TODO add your handling code here:
        pagina-=1;
        if(pagina>paginas||pagina<1)
        {
        pagina=1;
        }
            try {
            //Ojo con esto, aqui es donde se pone el nombre del archivo pdf, en este caso debe estar en el mismo
            File file = new File(ruta);
            //ubicaci�n del archivo pdf.
            RandomAccessFile raf = new RandomAccessFile(file, "r");
            FileChannel channel = raf.getChannel();
            MappedByteBuffer buf = channel.map(FileChannel.MapMode.READ_ONLY,0, channel.size());
            PDFFile pdffile = new PDFFile(buf);

            // Muestra la pagina indicada por la variable paginas
            PDFPage page = pdffile.getPage(pagina);
            paginas = pdffile.getNumPages(); ////numero de paginas del documento
            panel.useZoomTool(false);
            panel.showPage(page);

            }
            catch (Exception ex)
              {
              ex.printStackTrace();
              }
                        repaint();
                        panel.repaint();
    }//GEN-LAST:event_jbtnCargarAnteriorActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventAyuda dialog = new ventAyuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCargarAnterior;
    private javax.swing.JButton jbtnCargarSigiente;
    private javax.swing.JButton jbtnSalir;
    private org.edisoncor.gui.panel.PanelShadow jpanelSombra;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
